### ISSUE TITLE
How to add a conference

### ISSUE THREAD

**Issue by rdeutz** [ryanburgess/2016-conferences#2]
Hi,

I might missed the instructions somewhere, but how can I add a conference? Fork and make a PR?

Here what I would like to add
- JandBeyond
- Joomla! developer and sitebuilder conference
- 20-22 May 2016
- Barcelona, Spain

Cheers,
Robert

**Comment by ryanburgess** [comment]
Hey @rdeutz sorry I missed your question. I'll add how to contribute. I've actually created a JSON object with the conferences. If you add them to the JSON object and run `node index` it adds them to the read me

**Comment by ryanburgess** [comment]
I'll close this now because I've updated the `README.md` with instructions to contribute. Feel free to add!
